name: Release rikaikun
on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: '-d skips prepare and publish steps'
        required: false
        default: ''

jobs:
  release:
    name: Release rikaikun
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies and build
        run: npm ci && npm run build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release ${{ github.event.inputs.dryRun}}
