name: Update PR status
on:
  workflow_run:
    workflows: ['No unresolved comments']
    types:
      - completed

jobs:
  updatePRStatus:
    runs-on: ubuntu-latest
    steps:
      - name: 'Set PR Status'
        uses: Sibz/github-status-action@v1.1.5
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: ${{github.event.workflow_run.name}}
          description: 'Ensures comments have been resolved before merge. Re-run if stale.'
          state: ${{github.event.workflow_run.conclusion}}
          sha: ${{github.event.workflow_run.pull_requests[0].head.sha}}
          target_url: ${{github.event.workflow_run.html_url}}
# TODO: Make step for setting to pending.
# TODO: Use artifact upload to get more specific message.
